spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stores
    username: postgres
    password: papayaland
  mail:
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
